markdown: kramdown
highlighter: rouge

# gauges_id: 503c5af6613f5d0f19000027
# google_analytics_id: UA-50755011-1
# google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

repository: https://github.com/csulrong/csulrong.github.io
help_url: https://github.com/jekyll/jekyll-help

timezone: Asia/Shanghai

defaults:
  -
    scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "docs"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "news_item"


collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true
  tutorials:
    output: true

name: 欢迎来到荣亮的个人主页
description: 能工摹形，巧匠窃意。
url: https://csulrong.github.io

twitter:
  username: csulrong

logo: /img/logo-2x.png

encoding: utf-8

gems:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .gitignore
  - README.md
